version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: my-redis-stack
    ports:
      - "6379:6379"
 
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
    ports:
      - "5432:5432"